export const CONST_FACTURA = {
    codigoFactura: 'Código factura',
    cliente: 'Cliente',
    ciudad: 'Ciudad',
    nit: 'Nit',
    totalFactura: 'Total factura',
    subTotal: 'Sub total',
    color: 'Color',
    iva: 'Iva',
    retencion: 'Retención',
    fechaCreacion: 'Fecha de creación',
    estado: 'Estado',
    pagada: 'Pagada',
    fechaPago: 'Fecha de pago',
    id: 'Id',
    noResultados: 'No se encuentran resultados.',
    si: 'Si',
    no: 'No',
    // ...CONST_SHARED,
    // ...PATHS,
    // ...PERMISOS,
  };